### ISSUE TITLE
Can't build Wrangler on UDM Pro 1.8.5

### ISSUE THREAD

**Issue by tackynugget** [blackjid/inadyn-cloudflare#2]
I tried to follow the steps here on my UDM Pro running firmware 1.8.5, but was unsuccessful. Here are a few notes/points of clarification.

1. The **NPM** command must be run from within an **unifi-OS shell**

2. The **npm install -g @cloudflare/wrangler** command will error out:
`Error: Unsupported platform: Linux arm64`

3. While https://developers.cloudflare.com/workers/cli-wrangler/install-update#additional-installation-instructions lists Cargo as a work around, attempting to install wrangler via **cargo install wrangler** will also error out:
`error: linker 'cc' not found`
`= note: No such file or directory (os error 2)`
`error: aborting due to previous error`
`error: could not compile 'proc-macro2'`
`To learn more, run the command again with --verbose.`
`warning: build failed, waiting for other jobs to finish...`
`error: linker 'cc' not found`

4.  While **npm** has to be run from **unifi-os shell**, the Cargo installation cannot be run from within that shell.

It seems like we should be able to figure out the syntax of the inadyn backend and skip the wrangler bit and just craft an update sting to work with CloudFlare DDNS.

**Comment by blackjid** [comment]
Hi @OverengineeredNetwork 
You don't really need to run wrangler inside your UDM..
Wrangler is just a tool for deploying to cloudflare the worker that will serve as an endpoint for you dyniamic dns configuration.

**Comment by blackjid** [comment]
I have updated the readme with more details 
I hope now is easier to follow.
