### ISSUE TITLE
inadyn[23085]: DDNS server response: HTTP/1.1 404 Not Found

### ISSUE THREAD

**Issue by hasecbinusr** [blackjid/inadyn-cloudflare#4]
After implementing this worker as instructed in the readme, I ran `/usr/sbin/inadyn -n -s -C -f /run/inadyn.conf -1 -l debug --foreground` from the UDM shell (not Unifi-OS) to test if the integration worked.  No matter what I changed, I kept receiving the following:

```
inadyn[5237]: Sending alias table update to DDNS server: GET //update?hostname=<domain-name-here>&ip=XXX.XXX.XXX.XXX HTTP/1.0
Host: dyndns.<domain>.workers.dev
Authorization: Basic <hash>
User-Agent: inadyn/2.5 https://github.com/troglobit/inadyn/issues

inadyn[5237]: Successfully sent HTTPS request!
inadyn[5237]: Successfully received HTTPS response (866 bytes)!
inadyn[5237]: DDNS server response: HTTP/1.1 404 Not Found
...
inadyn[23085]: Fatal error in DDNS server response:
inadyn[23085]: [404 Not Found] 
inadyn[23085]: Error response from DDNS server, ignoring ...
```

It continued in this loop until I stopped the command.

After debugging the worker, I realized that the UDM controller UI bug was forcing a double forward slash on the GET path. 
 Changing line 30 of index.js resolved the issue:

```diff
  // Parse Url
  const requestUrl = url.parse(request.url, true)

-  if (requestUrl.pathname != '/update') {
+  if (requestUrl.pathname != '//update') {
    return new Response('', {
      headers: {
        'content-type': 'text/plain',
      },
      status: 404,
    })
  }
  const query = requestUrl.query
  const hostname = query.hostname
  const ip = query.ip
```

After publishing this change to the worker, the request worked as intended:

```
inadyn[26602]: Successfully sent HTTPS request!
inadyn[26602]: Successfully received HTTPS response (867 bytes)!
inadyn[26602]: DDNS server response: HTTP/1.1 200 OK
...
inadyn[26602]: Successful alias table update for <domain-name-here> => new IP# XXX.XXX.XXX.XXX
inadyn[26602]: Updating cache for <domain-name-here>
```

**Comment by blackjid** [comment]
hi @hasecbinusr 
What version of the UDM controller are you using?
I think there was a bug that was already fixed...

Today I realize that my instance wasn't working and I update the readme with the proper configuration.
You should not need to change the code

https://github.com/blackjid/inadyn-cloudflare/commit/954fad4cf22417c339887560ebb535e1f6adfff2

**Comment by hasecbinusr** [comment]
> hi @hasecbinusr
> What version of the UDM controller are you using?
> I think there was a bug that was already fixed...
> 
> Today I realize that my instance wasn't working and I update the readme with the proper configuration.
> You should not need to change the code
> 
> [954fad4](https://github.com/blackjid/inadyn-cloudflare/commit/954fad4cf22417c339887560ebb535e1f6adfff2)

The initial issue was in March, so I'm sure I was running whatever the current UDM controller version was on March 20th.  I am currently attempting this on UDM-Pro controller 6.2.26.  I reverted the code in index.js to your original code and rebuilt the worker.  The GET request is building correctly now, but I am receiving a 404 error again, but with a different Cloudflare response:

```
inadyn[6828]: Sending alias table update to DDNS server: GET /update?hostname=<domain-name-here>&ip=XXX.XXX.XXX.XXX HTTP/1.0
Host: dyndns.<domain>.workers.dev
Authorization: Basic <hash>
User-Agent: inadyn/2.8.1 https://github.com/troglobit/inadyn/issues

inadyn[6828]: Successfully sent HTTPS request!
inadyn[6828]: Successfully received HTTPS response (699/8191 bytes)!
inadyn[6828]: DDNS server response: HTTP/1.1 404 Not Found
Date: Mon, 26 Jul 2021 14:43:34 GMT
Content-Type: text/plain
Content-Length: 0
Connection: close
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=mbVIZ1oxWiRSSY8y3UrJAfjwIMa0K5sGUYm8jyrg217%2BCirxe2D9U41fJmXtus2Y1ouKjp3RdYYTuFqICauavJjEXlnhckFYV6BUKDYQVC9h0hhDflqMNtYNccBFE53zxb1%2ByeMSpTHYSlpqAEPSxY0G"}],"group":"cf-nel","max_age":604800}
NEL: {"report_to":"cf-nel","max_age":604800}
Server: cloudflare
CF-RAY: 674e66aaa8cc2836-DFW
alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400, h3=":443"; ma=86400
```
Did the Cloudflare API change for this request?

**Comment by blackjid** [comment]
mm, I'm not really sure, I can see that you are using inadyn 2.8.1, which is the latest...
I'm using 2.5., which is what I have in my UDM (not pro)

Maybe you should try to make the cloudflare provider for inadyn, which is in 2.8 but not in 2.5

https://github.com/troglobit/inadyn/blob/master/examples/cloudflare-ipv4-only.conf
```
provider cloudflare.com {
    username = zone.name
    password = api_token_important_read_comment
    hostname = hostname.zone.name
    ttl = 1 # optional, value of 1 is 'automatic'.
    proxied = false # optional.
}
```

I'm not sure if you can change and persist changes to the `/run/inadyn.conf` file

**Comment by blackjid** [comment]
I upgraded to 1.10.0 and now I have the latest inadyn version 2.8.1 on my UDM Base...

**Comment by hasecbinusr** [comment]
> I upgraded to 1.10.0 and now I have the latest inadyn version 2.8.1 on my UDM Base...

Is it working without issue for you? I'm wondering if I have a Cloudflare configuration issue.
