### ISSUE TITLE
Multi wan support ?

### ISSUE THREAD

**Issue by ashmodai6** [blackjid/inadyn-cloudflare#7]
First thanks a lot for this. I deployed it as proposed but I need to update both wan and wan2 ips thru ddns in cloudflare. 
UDM pro does not let you create two ddns client with the same provider (hummm) so I deployed two workers with different names dyndns and easydns, but I cannot get this to work properly. Both DNS entries always end up being updated ... with the same ip (from WAN1)
I looked at the generated inadyn.conf but indeed this conf file does not allow to specific different interfaces so I wonder how it is supposed to be able to work ? Thanks !

**Comment by ashmodai6** [comment]
I still don't understand how the stock implementation in unifyos is supposed to ever be working but I was able to get it to work by modifying manually the /run/inadyn.conf to add to each block respectively
checkip-command = "/sbin/ifconfig eth8 | grep 'inet addr'" 
and
checkip-command = "/sbin/ifconfig eth9 | grep 'inet addr'" 
since eth8 is wan1 and eth9 is wan2

so each block looks lilke

custom dyndns.MYZONE.workers.dev {
    hostname = "MYHOST.MYZONE.COM"
    username = "MYZONE.COM"
    password = "API_KEY"
    ddns-server = "dyndns.MYZONE.workers.dev"
    ddns-path = "/update?hostname=%h&ip=%i"
    checkip-command = "/sbin/ifconfig eth8 | grep 'inet addr'"
}

**Comment by blackjid** [comment]
did so does the manual config end up working??
